spring:
  profiles:
    active:
      - local
    group:
      local:
        - oauth

  mvc:
    log-request-details: true


logging:
  level:
    web: debug


jasypt:
  encryptor:
    bean: jasyptStringEncryptor
