spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(UEaXLk+nw8GEP/iUqdSczhFMVBhZFRwUcnDH+pLffN2kNRsUID8km2GI9COaqBTeMV2YhLCWnPbiPb+8z1ofNWuzYJWwIMaZB5ZXJGUdOek=)
            client-secret: ENC(sr8dPhNMHDqW2o3ym51z2YXPxH47ccwu1UMOZ6tTtw6VahMRbEl+y8g1mR3mvxWK)
            scope: email, profile

